// Do not edit. Generated by misc/build-tslibs.ts
  export const dom = {
  filename: "lib.dom.d.ts",
  version: "4hG/R46RQSoRnGRlLKMnhD9gaX4"
};
export const webworker = {
  filename: "lib.webworker.d.ts",
  version: "JvTccpIu9of2OjFw8xrHYjbBrVU"
};
export const scripter = {
  filename: "scripter-env.d.ts",
  version: "OTv3981fJru4/uRsfKhUXweO9a0"
};
export const figma = {
  filename: "figma.d.ts",
  version: "SPhe1CAPkagGPjiJ0QbGoQW5RvI"
};
