// Do not edit. Generated by misc/build-tslibs.js
export const dom = {
  filename: "lib.dom.d.ts",
  version: "+EviNZmp2POY3vxI1MwvwLsktEk"
};
export const webworker = {
  filename: "lib.webworker.d.ts",
  version: "nkpjZop6oiU0iz4a83cmigz6edo"
};
export const figpad = {
  filename: "figpad-env.d.ts",
  version: "HDW99XveQ/zUeXrkVIp2nYXM41w"
};
export const figma = {
  filename: "figma.d.ts",
  version: "3i2UyGhkhq7hH1R+aBcG+uqi490"
};
